# Generated by Django 4.2 on 2024-02-29 11:15

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='max_users',
            field=models.PositiveIntegerField(default=10, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='min_users',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='students',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время старта!'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало подписки'),
        ),
    ]
