# Generated by Django 4.2 on 2024-02-29 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_system', '0002_alter_groupp_max_users_alter_groupp_min_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
