# Generated by Django 4.2 on 2024-02-29 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_system', '0003_alter_groupp_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='training_system.product'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_lessons', to='training_system.product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='training_system.product'),
        ),
    ]
