# Generated by Django 4.2 on 2024-02-29 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_system', '0004_alter_groupp_product_id_alter_groupp_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='min_users',
            field=models.PositiveIntegerField(default=5, verbose_name='Минимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
